# base site information
baseURL: https://zmsy.co/
title: zmsy.co
languageCode: en-us
DefaultContentLanguage: "en"

# custom parameters
params:
  AuthorName: Zach Morrissey
  AuthorEmail: zachjmorrissey+zmsy@gmail.com
  GithubUser: zmsy
  LinkedInUser: zmsy
  LinkedInUrl: https://www.linkedin.com/in/zmsy
  TwitterHandle: _zmsy
  HowieInstagram: https://www.instagram.com/howiethesamoyed
  nav:
    - Url: /
      Name: Home
    - Url: /blog
      Name: Blog
    - Url: /recipes
      Name: Recipes
    - Url: /about
      Name: About
  icons:
    - Icon: icon-linkedin-square
      Alt: View my LinkedIn profile.
      Url: https://www.linkedin.com/in/zmsy
    - Icon: icon-github
      Alt: Check out my Github.
      Url: https://github.com/zmsy
    - Icon: icon-twitter
      Alt: Check out my sparsely used Twitter account.
      Url: https://twitter.com/_zmsy

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: manni
    tabWidth: 4
  goldmark:
    renderer:
      unsafe: true

module:
  mounts:
  - source: content
    target: content
  - source: static
    target: static
  - source: layouts
    target: layouts
  - source: assets
    target: assets
  - source: archetypes
    target: archetypes
  - source: node_modules/bulma
    target: assets/styles/bulma

# site settings
enableEmoji: true
enableInlineShortcodes: true
enableGitInfo: true
enableRobotsTXT: true
canonifyURLs: true
disableKinds: [“taxonomy”, “taxonomyTerm”]
googleAnalytics: UA-104524581-1
paginate: 5

# javascript bundling information
build:
  noJSConfigInAssets: true
