name: Build & Deploy to Github Pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # comment this line out if the build ever uses `.LastMod` or `.GitInfo`
          # blocks in any of the templates
          fetch-depth: 0

      - name: Setup NPM
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.100.1"
          extended: true

      - name: NPM Install
        run: npm install

      - name: NPM Check Formatting
        run: npm run format-check

        # zustand/preact package patching
      - name: NPM Patch Package
        run: npm run patch

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
