name: Validate

on: [pull_request]

jobs:
  check:
    name: Validate pull request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2
        with:
          # comment this line out if the build ever uses `.LastMod` or `.GitInfo`
          # blocks in any of the templates
          fetch-depth: 0
      - name: Build astro site
        uses: withastro/action@v0
        with:
          node-version: 18
      - name: Run astro check
        run: npm run astro check
      - name: Run prettier check
        run: npm run format:check
      - name: Run eslint check
        run: npm run lint:check
